[package]
name = "mercury-ws"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license-file.workspace = true

[dependencies]
mercury-contracts = { workspace = true }
mercury-core = { workspace = true }
mercury-models = { workspace = true }
mercury-db = { workspace = true }
mercury-util = { workspace = true }
mercury-relay = { path = "../mercury-relay" }
axum = { workspace = true }
tokio = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
jsonwebtoken = { workspace = true }
futures-util = "0.3"
moka = { workspace = true }
dashmap = { workspace = true }
governor = { workspace = true }
flate2 = "1"

[dev-dependencies]
sqlx = { workspace = true }
mercury-media = { workspace = true }
tempfile = { workspace = true }
anyhow = { workspace = true }
tokio-tungstenite = { workspace = true }
