-- Paracord Schema (SQLite)

CREATE TABLE users (
    id              BIGINT PRIMARY KEY,
    username        VARCHAR(32) NOT NULL,
    discriminator   SMALLINT NOT NULL DEFAULT 0,
    email           VARCHAR(255) NOT NULL UNIQUE,
    password_hash   VARCHAR(255) NOT NULL,
    display_name    VARCHAR(32),
    avatar_hash     VARCHAR(64),
    banner_hash     VARCHAR(64),
    bio             VARCHAR(190),
    accent_color    INTEGER,
    locale          VARCHAR(10) DEFAULT 'en-US',
    flags           INTEGER NOT NULL DEFAULT 0,
    mfa_enabled     BOOLEAN NOT NULL DEFAULT FALSE,
    created_at      TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at      TEXT NOT NULL DEFAULT (datetime('now')),
    UNIQUE(username, discriminator)
);

CREATE TABLE guilds (
    id              BIGINT PRIMARY KEY,
    name            VARCHAR(100) NOT NULL,
    description     VARCHAR(1000),
    icon_hash       VARCHAR(64),
    banner_hash     VARCHAR(64),
    owner_id        BIGINT NOT NULL REFERENCES users(id),
    features        INTEGER NOT NULL DEFAULT 0,
    system_channel_id  BIGINT,
    vanity_url_code    VARCHAR(32) UNIQUE,
    max_members     INTEGER NOT NULL DEFAULT 500000,
    preferred_locale VARCHAR(10) DEFAULT 'en-US',
    created_at      TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at      TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE channels (
    id              BIGINT PRIMARY KEY,
    guild_id        BIGINT REFERENCES guilds(id) ON DELETE CASCADE,
    name            VARCHAR(100),
    topic           VARCHAR(1024),
    channel_type    SMALLINT NOT NULL,
    position        INTEGER NOT NULL DEFAULT 0,
    parent_id       BIGINT REFERENCES channels(id),
    nsfw            BOOLEAN NOT NULL DEFAULT FALSE,
    rate_limit_per_user INTEGER NOT NULL DEFAULT 0,
    bitrate         INTEGER DEFAULT 64000,
    user_limit      INTEGER DEFAULT 0,
    last_message_id BIGINT,
    created_at      TEXT NOT NULL DEFAULT (datetime('now')),
    updated_at      TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX idx_channels_guild_id ON channels(guild_id);

CREATE TABLE channel_overwrites (
    channel_id      BIGINT NOT NULL REFERENCES channels(id) ON DELETE CASCADE,
    target_id       BIGINT NOT NULL,
    target_type     SMALLINT NOT NULL,
    allow_perms     BIGINT NOT NULL DEFAULT 0,
    deny_perms      BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (channel_id, target_id)
);

CREATE TABLE messages (
    id              BIGINT PRIMARY KEY,
    channel_id      BIGINT NOT NULL REFERENCES channels(id) ON DELETE CASCADE,
    author_id       BIGINT NOT NULL REFERENCES users(id),
    content         TEXT,
    message_type    SMALLINT NOT NULL DEFAULT 0,
    flags           INTEGER NOT NULL DEFAULT 0,
    edited_at       TEXT,
    pinned          BOOLEAN NOT NULL DEFAULT FALSE,
    nonce           VARCHAR(64),
    reference_id    BIGINT,
    thread_id       BIGINT REFERENCES channels(id),
    created_at      TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX idx_messages_channel_created ON messages(channel_id, id DESC);
CREATE INDEX idx_messages_author ON messages(author_id);

CREATE TABLE message_embeds (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id      BIGINT NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
    embed_data      TEXT NOT NULL
);

CREATE TABLE attachments (
    id              BIGINT PRIMARY KEY,
    message_id      BIGINT REFERENCES messages(id) ON DELETE CASCADE,
    filename        VARCHAR(255) NOT NULL,
    content_type    VARCHAR(127),
    size            INTEGER NOT NULL,
    url             TEXT NOT NULL,
    width           INTEGER,
    height          INTEGER
);
CREATE INDEX idx_attachments_message_id ON attachments(message_id);

CREATE TABLE reactions (
    message_id      BIGINT NOT NULL REFERENCES messages(id) ON DELETE CASCADE,
    user_id         BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    emoji_id        BIGINT,
    emoji_name      VARCHAR(64) NOT NULL,
    created_at      TEXT NOT NULL DEFAULT (datetime('now')),
    PRIMARY KEY (message_id, user_id, emoji_name)
);

CREATE TABLE members (
    user_id         BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    guild_id        BIGINT NOT NULL REFERENCES guilds(id) ON DELETE CASCADE,
    nick            VARCHAR(32),
    avatar_hash     VARCHAR(64),
    joined_at       TEXT NOT NULL DEFAULT (datetime('now')),
    deaf            BOOLEAN NOT NULL DEFAULT FALSE,
    mute            BOOLEAN NOT NULL DEFAULT FALSE,
    communication_disabled_until TEXT,
    PRIMARY KEY (user_id, guild_id)
);
CREATE INDEX idx_members_guild ON members(guild_id);

CREATE TABLE roles (
    id              BIGINT PRIMARY KEY,
    guild_id        BIGINT NOT NULL REFERENCES guilds(id) ON DELETE CASCADE,
    name            VARCHAR(100) NOT NULL,
    color           INTEGER NOT NULL DEFAULT 0,
    hoist           BOOLEAN NOT NULL DEFAULT FALSE,
    position        INTEGER NOT NULL DEFAULT 0,
    permissions     BIGINT NOT NULL DEFAULT 0,
    managed         BOOLEAN NOT NULL DEFAULT FALSE,
    mentionable     BOOLEAN NOT NULL DEFAULT FALSE,
    created_at      TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX idx_roles_guild ON roles(guild_id);

CREATE TABLE member_roles (
    user_id         BIGINT NOT NULL,
    guild_id        BIGINT NOT NULL,
    role_id         BIGINT NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, guild_id, role_id),
    FOREIGN KEY (user_id, guild_id) REFERENCES members(user_id, guild_id) ON DELETE CASCADE
);

CREATE TABLE invites (
    code            VARCHAR(16) PRIMARY KEY,
    guild_id        BIGINT NOT NULL REFERENCES guilds(id) ON DELETE CASCADE,
    channel_id      BIGINT NOT NULL REFERENCES channels(id) ON DELETE CASCADE,
    inviter_id      BIGINT REFERENCES users(id),
    max_uses        INTEGER DEFAULT 0,
    uses            INTEGER NOT NULL DEFAULT 0,
    max_age         INTEGER DEFAULT 86400,
    temporary       BOOLEAN NOT NULL DEFAULT FALSE,
    created_at      TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE bans (
    user_id         BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    guild_id        BIGINT NOT NULL REFERENCES guilds(id) ON DELETE CASCADE,
    reason          VARCHAR(512),
    banned_by       BIGINT REFERENCES users(id),
    created_at      TEXT NOT NULL DEFAULT (datetime('now')),
    PRIMARY KEY (user_id, guild_id)
);

CREATE TABLE audit_log_entries (
    id              BIGINT PRIMARY KEY,
    guild_id        BIGINT NOT NULL REFERENCES guilds(id) ON DELETE CASCADE,
    user_id         BIGINT NOT NULL REFERENCES users(id),
    action_type     SMALLINT NOT NULL,
    target_id       BIGINT,
    reason          VARCHAR(512),
    changes         TEXT,
    created_at      TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX idx_audit_log_guild ON audit_log_entries(guild_id, created_at DESC);

CREATE TABLE relationships (
    user_id         BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    target_id       BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    rel_type        SMALLINT NOT NULL,
    created_at      TEXT NOT NULL DEFAULT (datetime('now')),
    PRIMARY KEY (user_id, target_id)
);

CREATE TABLE dm_recipients (
    channel_id      BIGINT NOT NULL REFERENCES channels(id) ON DELETE CASCADE,
    user_id         BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    PRIMARY KEY (channel_id, user_id)
);
CREATE INDEX idx_dm_recipients_user_id ON dm_recipients(user_id);

CREATE TABLE emojis (
    id              BIGINT PRIMARY KEY,
    guild_id        BIGINT NOT NULL REFERENCES guilds(id) ON DELETE CASCADE,
    name            VARCHAR(32) NOT NULL,
    creator_id      BIGINT REFERENCES users(id),
    animated        BOOLEAN NOT NULL DEFAULT FALSE,
    created_at      TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE webhooks (
    id              BIGINT PRIMARY KEY,
    guild_id        BIGINT NOT NULL REFERENCES guilds(id) ON DELETE CASCADE,
    channel_id      BIGINT NOT NULL REFERENCES channels(id) ON DELETE CASCADE,
    creator_id      BIGINT REFERENCES users(id),
    name            VARCHAR(80) NOT NULL,
    token           VARCHAR(128) NOT NULL UNIQUE,
    created_at      TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE automod_rules (
    id              BIGINT PRIMARY KEY,
    guild_id        BIGINT NOT NULL REFERENCES guilds(id) ON DELETE CASCADE,
    name            VARCHAR(100) NOT NULL,
    creator_id      BIGINT REFERENCES users(id),
    event_type      SMALLINT NOT NULL,
    trigger_type    SMALLINT NOT NULL,
    trigger_metadata TEXT NOT NULL DEFAULT '{}',
    actions         TEXT NOT NULL DEFAULT '[]',
    enabled         BOOLEAN NOT NULL DEFAULT TRUE,
    created_at      TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE user_settings (
    user_id         BIGINT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
    theme           VARCHAR(32) DEFAULT 'dark',
    custom_css      TEXT,
    locale          VARCHAR(10) DEFAULT 'en-US',
    message_display VARCHAR(16) DEFAULT 'cozy',
    notifications   TEXT NOT NULL DEFAULT '{}',
    keybinds        TEXT NOT NULL DEFAULT '{}',
    updated_at      TEXT NOT NULL DEFAULT (datetime('now'))
);

CREATE TABLE read_states (
    user_id         BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    channel_id      BIGINT NOT NULL REFERENCES channels(id) ON DELETE CASCADE,
    last_message_id BIGINT NOT NULL DEFAULT 0,
    mention_count   INTEGER NOT NULL DEFAULT 0,
    PRIMARY KEY (user_id, channel_id)
);

CREATE TABLE voice_states (
    user_id         BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    guild_id        BIGINT REFERENCES guilds(id) ON DELETE CASCADE,
    channel_id      BIGINT NOT NULL REFERENCES channels(id) ON DELETE CASCADE,
    session_id      VARCHAR(64) NOT NULL,
    self_mute       BOOLEAN NOT NULL DEFAULT FALSE,
    self_deaf       BOOLEAN NOT NULL DEFAULT FALSE,
    self_stream     BOOLEAN NOT NULL DEFAULT FALSE,
    self_video      BOOLEAN NOT NULL DEFAULT FALSE,
    suppress        BOOLEAN NOT NULL DEFAULT FALSE,
    PRIMARY KEY (user_id)
);

CREATE TABLE federation_events (
    event_id        VARCHAR(255) PRIMARY KEY,
    room_id         VARCHAR(255) NOT NULL,
    event_type      VARCHAR(255) NOT NULL,
    sender          VARCHAR(255) NOT NULL,
    origin_server   VARCHAR(255) NOT NULL,
    origin_ts       BIGINT NOT NULL,
    content         TEXT NOT NULL,
    depth           BIGINT NOT NULL,
    state_key       VARCHAR(255),
    signatures      TEXT NOT NULL,
    created_at      TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX idx_fed_events_room ON federation_events(room_id, depth);

CREATE TABLE federation_server_keys (
    server_name     VARCHAR(255) NOT NULL,
    key_id          VARCHAR(255) NOT NULL,
    public_key      TEXT NOT NULL,
    valid_until     BIGINT NOT NULL,
    PRIMARY KEY (server_name, key_id)
);

CREATE INDEX idx_channel_overwrites_channel_id ON channel_overwrites(channel_id);
