-- Federation transport hardening and delivery durability.

CREATE TABLE IF NOT EXISTS federation_peer_trust_state (
    server_name             VARCHAR(255) PRIMARY KEY,
    mode                    VARCHAR(16) NOT NULL DEFAULT 'allow'
                                CHECK (mode IN ('allow', 'block', 'quarantine')),
    reason                  TEXT,
    quarantined_until_ms    BIGINT,
    updated_at_ms           BIGINT NOT NULL DEFAULT (CAST(strftime('%s', 'now') AS INTEGER) * 1000)
);

-- Backfill trust state from existing trusted flag.
INSERT INTO federation_peer_trust_state (server_name, mode, reason)
SELECT
    fs.server_name,
    CASE WHEN fs.trusted THEN 'allow' ELSE 'block' END,
    'Backfilled from federated_servers.trusted'
FROM federated_servers fs
WHERE NOT EXISTS (
    SELECT 1
    FROM federation_peer_trust_state pts
    WHERE pts.server_name = fs.server_name
);

CREATE TABLE IF NOT EXISTS federation_transport_replay_cache (
    origin_server           VARCHAR(255) NOT NULL,
    signature_hash          VARCHAR(128) NOT NULL,
    request_ts              BIGINT NOT NULL,
    created_at_ms           BIGINT NOT NULL DEFAULT (CAST(strftime('%s', 'now') AS INTEGER) * 1000),
    PRIMARY KEY (origin_server, signature_hash)
);

CREATE INDEX IF NOT EXISTS idx_fed_transport_replay_created
    ON federation_transport_replay_cache(created_at_ms);

CREATE TABLE IF NOT EXISTS federation_outbound_queue (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    destination_server      VARCHAR(255) NOT NULL,
    event_id                VARCHAR(255) NOT NULL,
    room_id                 VARCHAR(255) NOT NULL,
    event_type              VARCHAR(255) NOT NULL,
    sender                  VARCHAR(255) NOT NULL,
    origin_server           VARCHAR(255) NOT NULL,
    origin_ts               BIGINT NOT NULL,
    content                 TEXT NOT NULL,
    depth                   BIGINT NOT NULL,
    state_key               VARCHAR(255),
    signatures              TEXT NOT NULL,
    attempt_count           INTEGER NOT NULL DEFAULT 0,
    next_attempt_at_ms      BIGINT NOT NULL DEFAULT (CAST(strftime('%s', 'now') AS INTEGER) * 1000),
    last_error              TEXT,
    created_at_ms           BIGINT NOT NULL DEFAULT (CAST(strftime('%s', 'now') AS INTEGER) * 1000),
    updated_at_ms           BIGINT NOT NULL DEFAULT (CAST(strftime('%s', 'now') AS INTEGER) * 1000),
    UNIQUE (destination_server, event_id)
);

CREATE INDEX IF NOT EXISTS idx_fed_outbound_due
    ON federation_outbound_queue(next_attempt_at_ms, destination_server);

CREATE TABLE IF NOT EXISTS federation_delivery_attempts (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    destination_server      VARCHAR(255) NOT NULL,
    event_id                VARCHAR(255) NOT NULL,
    success                 BOOLEAN NOT NULL,
    status_code             INTEGER,
    error                   TEXT,
    latency_ms              BIGINT,
    attempted_at_ms         BIGINT NOT NULL DEFAULT (CAST(strftime('%s', 'now') AS INTEGER) * 1000)
);

CREATE INDEX IF NOT EXISTS idx_fed_delivery_attempts_event
    ON federation_delivery_attempts(destination_server, event_id, attempted_at_ms DESC);
